name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'


    - name: Create application.properties
      run: echo "${{ secrets.APPLICATION }}" > src/main/resources/application.properties

    - name: Build with Gradle Wrapper
      run: ./gradlew build

    - name: Docker build and push
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/focus-be .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_USERNAME }}/focus-be
    
    - name: EC2 Pull
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.PRIVATE_KEY }}
        script: |
          # Login
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          
          # Pull the new image
          docker pull ${{ secrets.DOCKER_USERNAME }}/focus-be
          
          # Stop and remove the existing container
          docker stop focus-be
          docker rm focus-be

          # Remove the existing image
          docker rmi ${{ secrets.DOCKER_USERNAME }}/focus-be
          
          # Run the application container
          docker run -d -p 80:8080 -p 443:8443 \
            -v /home/ubuntu/hpass.shop/cert1.pem:/usr/local/tomcat/conf/cert.pem \
            -v /home/ubuntu/hpass.shop/privkey1.pem:/usr/local/tomcat/conf/privkey.pem \
            -v /home/ubuntu/hpass.shop/chain1.pem:/usr/local/tomcat/conf/chain.pem \
            -v /home/ubuntu/server.xml:/usr/local/tomcat/conf/server.xml \
            --name focus-be ${{ secrets.DOCKER_USERNAME }}/focus-be
